---
galaxy_info:
  role_name: k3s-server
  author: infra-k3s
  description: Install and configure K3s server (control plane)
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: EL
      versions:
        - "8"
        - "9"

dependencies:
  - role: k3s-prereq
