apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: apps
type: Opaque
stringData:
    secret_key: ENC[AES256_GCM,data:wtwf/+7GsFofgILV6QUk5o7z3N3zhSNSr/01ZhBfETTbYD3pWgTtd4nLTFgqlqSCfeSSyRiwMeX7YM1UfotG9nWP3Ao2uQyFI14AYunANRI=,iv:HX0VGmHzrv/oQ2IPR8S0pPu0CiaEEotISsMlufctsR8=,tag:Z2+TCTPG67/2JEYi1bAHiQ==,type:str]
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNEUvU05iZXNiV053ejJ4
            T1UrYzIvM05pZTNGaFpUS2ZDMWVtajJjb0RRClNsRm1Za29STGNKdU4wb1ZSdDRo
            Rkx1cEc0WXdBOHIzNXlGM3V3QmtFQ1kKLS0tIENYOVJ5MXBvcVVGQktYWm5oOXA1
            YklqVGhoWEhvd0prV2NaWnM4UTM3blEKCBV+tS9/wssT+ygOscUk1OmPPmV+8SVE
            wbgvpLYun0BOYMcgTw+jMZWIq75LmiPC6b23PMlV9AecrP0Fg6miBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T03:46:33Z"
    mac: ENC[AES256_GCM,data:MauDvFbfvRdannWF7jcY+H8o4LiDDBkJINf9gGdhBShdRNaLQghv+rmaDR0YLFXYvqYwg4ozZVx9u8zOvTJzHDKpJB9PcQgsvDF+6uCxufTnFBjO+/jgWJn62OhDB5Y7EdQbpFQKhEQiaysmLShRj4K6uu0rirK67OlMzoDqSZg=,iv:9+CqFVBStXC/2XDKaH6Lr+jbZXxUjZ1HahCpuFV+8Gg=,tag:51rgWoQsh4KXwnU84P+c+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
