apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:51LwP9jEekvBwIcEQktKuVZXH8bX+c//urMl5Nb68vgxCyrfW7mLKg==,iv:jeuxRPnbkOc7Ucjvp0D1vyZa59DmgGBSkPHq8No4n3c=,tag:kJrU6LxdTJHV3ajdNRdxKQ==,type:str]
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVm9waHBBMEpxaDFPZ3Yw
            Z2xMQjJ6Z1BaZzZUZm9WbDAxaFFEdXcrZmlzCjFlMjRabW8wcWYzOXpPV0dMbnhC
            Q3I2RjlsVENMQ0Y1Y0p1bWFiZTlia0EKLS0tIFNuV1NUQW1YRlMweDhUb3JpejlB
            SEJHc3FvbTFkenp5WXhVY1B3YkIzQk0KBvp1bQJMYqcpX2NG0knJzJSA7emhHhyN
            dla+DrNWnaqqYhbHSTaVL5qArky9uxLpVcTKPNqY9aK6Q8A+AWCPRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T04:04:42Z"
    mac: ENC[AES256_GCM,data:fNRxmtBWcdrUvur9S6XLMSi7scA5Ezwje8rYey98bk4jG/dkVbMd7GcYZu2jZ+9b8/+9z+XOW8+0g3PHjeQc6m7Z8B4ukAT4GBJpkEkVwhCitnA0q2r5L0B1x4UoAh0Mg5eVX7ZCbH/SFSs1eBd+Xyy5aq1ZuUeD/f6LX0lnPh0=,iv:KaJ6czrUE3E868WHVw7MyeZTTF9R/PK0YGp6pQyTHd8=,tag:8hQdjYZka1oQpSxeQoRJjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:VFCqwrWVzThdLYXiR02Ada93WAHYsZiRFWbeH22KPFN/iX9f7lK6ww==,iv:2CBifw2u2aTR2KXQd8XHPFtETDwvRyBb17sKC+DbBtw=,tag:Zp7tR8yLUJ2hDv/dn/J4Yw==,type:str]
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVm9waHBBMEpxaDFPZ3Yw
            Z2xMQjJ6Z1BaZzZUZm9WbDAxaFFEdXcrZmlzCjFlMjRabW8wcWYzOXpPV0dMbnhC
            Q3I2RjlsVENMQ0Y1Y0p1bWFiZTlia0EKLS0tIFNuV1NUQW1YRlMweDhUb3JpejlB
            SEJHc3FvbTFkenp5WXhVY1B3YkIzQk0KBvp1bQJMYqcpX2NG0knJzJSA7emhHhyN
            dla+DrNWnaqqYhbHSTaVL5qArky9uxLpVcTKPNqY9aK6Q8A+AWCPRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T04:04:42Z"
    mac: ENC[AES256_GCM,data:fNRxmtBWcdrUvur9S6XLMSi7scA5Ezwje8rYey98bk4jG/dkVbMd7GcYZu2jZ+9b8/+9z+XOW8+0g3PHjeQc6m7Z8B4ukAT4GBJpkEkVwhCitnA0q2r5L0B1x4UoAh0Mg5eVX7ZCbH/SFSs1eBd+Xyy5aq1ZuUeD/f6LX0lnPh0=,iv:KaJ6czrUE3E868WHVw7MyeZTTF9R/PK0YGp6pQyTHd8=,tag:8hQdjYZka1oQpSxeQoRJjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
