apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:QhlbeGY=,iv:T1yKealOpDsE/tBObKZY3TgzCPI+TR8cTR7gDSb8oZ8=,tag:BZBLBfurxtPUUKgO7V/jhQ==,type:str]
    admin-password: ENC[AES256_GCM,data:ng+o9dXBJAvU,iv:aMEkMDNmxETRCldAa9Hcg8pH5qcBnX1yVQMWXaeyalg=,tag:X3/ICsZUYCdmbBr7aqywJA==,type:str]
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreS90ME95RnBQZXdVbkZU
            aGhnWFJUYnlHQWF5RnM1Wk1JdnJSYVJld0ZVCkRQQ0xidnlGRUtRdG9RdXVmL2hQ
            bkdoR0hvNDFsOHROcW4zMHpPajlQcEkKLS0tIHM4SHJnR04zanZ4bklDMTQ5UkNP
            eDY5NFVuTTM1NTBWODNYdVFON3ptRmsKhRa8kRrzo1Q+JnUHn2enA6JOMZTF5pDY
            R6jbA6lrvOBwqyDV6rs9G9cXFAqAcPy6MnaHbyQ9u0h0IqjS7M61Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T05:48:07Z"
    mac: ENC[AES256_GCM,data:w9vTtST3oJwg+PM9IM9kJNXo2aNxL9VexDOF1Gr8RlyG65HisztJ5D4jfMNT4xGWnJ6SKv5xV4++UoVdhFMGBLMNB6dVjNf+FjVN+noXel/DA7MSbsFFqvWUQNl5TFB/VVRVIFuFh6zqHkRkBrfbYRztNt6Wso8RGX8CYOEW13E=,iv:tFIAPzWIJOgRGnrBXmYsPgHfsPf8EzCN4hR2t0Doixw=,tag:H3iApHtFK7s9NYtOc6mkyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
