apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:ng+o9dXBJAvU,iv:aMEkMDNmxETRCldAa9Hcg8pH5qcBnX1yVQMWXaeyalg=,tag:X3/ICsZUYCdmbBr7aqywJA==,type:str]
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreS90ME95RnBQZXdVbkZU
            aGhnWFJUYnlHQWF5RnM1Wk1JdnJSYVJld0ZVCkRQQ0xidnlGRUtRdG9RdXVmL2hQ
            bkdoR0hvNDFsOHROcW4zMHpPajlQcEkKLS0tIHM4SHJnR04zanZ4bklDMTQ5UkNP
            eDY5NFVuTTM1NTBWODNYdVFON3ptRmsKhRa8kRrzo1Q+JnUHn2enA6JOMZTF5pDY
            R6jbA6lrvOBwqyDV6rs9G9cXFAqAcPy6MnaHbyQ9u0h0IqjS7M61Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T03:46:18Z"
    mac: ENC[AES256_GCM,data:GHLiD/Y3f1wbcMPiS6/dws0NNFM5c9uNeB4vMQ8Nj3mwhRorOLqpSlkqGMxvuqvZBbMdLweBF1SYxRJtnn2siVWrmhBw5FfvZFrGsejmAkP5B1/n9bD0nTEj13j1BMVxm0mvdApQ/a1NvCAdcw3as/d2PEA6JjuO4YtWOfg7ctk=,iv:p9lacdiwHVs/f8d9MCOrWcwNgZoOL2Q1EuswNmlQbH8=,tag:wiuBHC7YqQAmb2RgYZId4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
