apiVersion: v1
kind: Namespace
metadata:
    name: external-dns
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNnJWKzdpZFl3azl6WVBS
            WkVPcFRLUlo3cEVUQ0FUa0lTbzY4S3BWMXpvCjJFdEh4MjQ0Ry9CTWEvSVFDdG92
            VWJqaFNFUWl5ZFNHNW0yY3Z2UmxIVEEKLS0tIEQ1Z2lXSGF2RXNEazVZcWEvbEEy
            b3VXNmo3WCtGMytrZmNjU2NXT1hQZ2cKcnZqut0haeOniZQcUNDX6BAYT3iy532k
            TDaJ2PhNi6TkuUfLeV78KV50+wdgD8M34Bptg3qF6JND/yCQKjRVWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T05:09:02Z"
    mac: ENC[AES256_GCM,data:ankZZQRakqG55jytiW3khlHaQjTPOkj4yW1+WbitSgVCZjC2f0wFFKrcf3Y99HEy4j+9OT15dr7ZeIL8NrxnBTk/HsSswasuXPP9KahkLOarLqtlnklVr4eY9AqaMxDUXzpwFHQqp4mNV0+dDztVaZHYplfmo2yB34L3YlD2ba4=,iv:NpYbBI6u5HJXeKs4/AmwFhfL8BWxSXBogOdVjUSL1nQ=,tag:o/X8vBo6SPFrO9qmTKwcbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Namespace
metadata:
    name: cert-manager
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNnJWKzdpZFl3azl6WVBS
            WkVPcFRLUlo3cEVUQ0FUa0lTbzY4S3BWMXpvCjJFdEh4MjQ0Ry9CTWEvSVFDdG92
            VWJqaFNFUWl5ZFNHNW0yY3Z2UmxIVEEKLS0tIEQ1Z2lXSGF2RXNEazVZcWEvbEEy
            b3VXNmo3WCtGMytrZmNjU2NXT1hQZ2cKcnZqut0haeOniZQcUNDX6BAYT3iy532k
            TDaJ2PhNi6TkuUfLeV78KV50+wdgD8M34Bptg3qF6JND/yCQKjRVWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T05:09:02Z"
    mac: ENC[AES256_GCM,data:ankZZQRakqG55jytiW3khlHaQjTPOkj4yW1+WbitSgVCZjC2f0wFFKrcf3Y99HEy4j+9OT15dr7ZeIL8NrxnBTk/HsSswasuXPP9KahkLOarLqtlnklVr4eY9AqaMxDUXzpwFHQqp4mNV0+dDztVaZHYplfmo2yB34L3YlD2ba4=,iv:NpYbBI6u5HJXeKs4/AmwFhfL8BWxSXBogOdVjUSL1nQ=,tag:o/X8vBo6SPFrO9qmTKwcbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Namespace
metadata:
    name: monitoring
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNnJWKzdpZFl3azl6WVBS
            WkVPcFRLUlo3cEVUQ0FUa0lTbzY4S3BWMXpvCjJFdEh4MjQ0Ry9CTWEvSVFDdG92
            VWJqaFNFUWl5ZFNHNW0yY3Z2UmxIVEEKLS0tIEQ1Z2lXSGF2RXNEazVZcWEvbEEy
            b3VXNmo3WCtGMytrZmNjU2NXT1hQZ2cKcnZqut0haeOniZQcUNDX6BAYT3iy532k
            TDaJ2PhNi6TkuUfLeV78KV50+wdgD8M34Bptg3qF6JND/yCQKjRVWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T05:09:02Z"
    mac: ENC[AES256_GCM,data:ankZZQRakqG55jytiW3khlHaQjTPOkj4yW1+WbitSgVCZjC2f0wFFKrcf3Y99HEy4j+9OT15dr7ZeIL8NrxnBTk/HsSswasuXPP9KahkLOarLqtlnklVr4eY9AqaMxDUXzpwFHQqp4mNV0+dDztVaZHYplfmo2yB34L3YlD2ba4=,iv:NpYbBI6u5HJXeKs4/AmwFhfL8BWxSXBogOdVjUSL1nQ=,tag:o/X8vBo6SPFrO9qmTKwcbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Namespace
metadata:
    name: apps
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNnJWKzdpZFl3azl6WVBS
            WkVPcFRLUlo3cEVUQ0FUa0lTbzY4S3BWMXpvCjJFdEh4MjQ0Ry9CTWEvSVFDdG92
            VWJqaFNFUWl5ZFNHNW0yY3Z2UmxIVEEKLS0tIEQ1Z2lXSGF2RXNEazVZcWEvbEEy
            b3VXNmo3WCtGMytrZmNjU2NXT1hQZ2cKcnZqut0haeOniZQcUNDX6BAYT3iy532k
            TDaJ2PhNi6TkuUfLeV78KV50+wdgD8M34Bptg3qF6JND/yCQKjRVWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T05:09:02Z"
    mac: ENC[AES256_GCM,data:ankZZQRakqG55jytiW3khlHaQjTPOkj4yW1+WbitSgVCZjC2f0wFFKrcf3Y99HEy4j+9OT15dr7ZeIL8NrxnBTk/HsSswasuXPP9KahkLOarLqtlnklVr4eY9AqaMxDUXzpwFHQqp4mNV0+dDztVaZHYplfmo2yB34L3YlD2ba4=,iv:NpYbBI6u5HJXeKs4/AmwFhfL8BWxSXBogOdVjUSL1nQ=,tag:o/X8vBo6SPFrO9qmTKwcbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Namespace
metadata:
    name: velero
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNnJWKzdpZFl3azl6WVBS
            WkVPcFRLUlo3cEVUQ0FUa0lTbzY4S3BWMXpvCjJFdEh4MjQ0Ry9CTWEvSVFDdG92
            VWJqaFNFUWl5ZFNHNW0yY3Z2UmxIVEEKLS0tIEQ1Z2lXSGF2RXNEazVZcWEvbEEy
            b3VXNmo3WCtGMytrZmNjU2NXT1hQZ2cKcnZqut0haeOniZQcUNDX6BAYT3iy532k
            TDaJ2PhNi6TkuUfLeV78KV50+wdgD8M34Bptg3qF6JND/yCQKjRVWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T05:09:02Z"
    mac: ENC[AES256_GCM,data:ankZZQRakqG55jytiW3khlHaQjTPOkj4yW1+WbitSgVCZjC2f0wFFKrcf3Y99HEy4j+9OT15dr7ZeIL8NrxnBTk/HsSswasuXPP9KahkLOarLqtlnklVr4eY9AqaMxDUXzpwFHQqp4mNV0+dDztVaZHYplfmo2yB34L3YlD2ba4=,iv:NpYbBI6u5HJXeKs4/AmwFhfL8BWxSXBogOdVjUSL1nQ=,tag:o/X8vBo6SPFrO9qmTKwcbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Namespace
metadata:
    name: tailscale
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNnJWKzdpZFl3azl6WVBS
            WkVPcFRLUlo3cEVUQ0FUa0lTbzY4S3BWMXpvCjJFdEh4MjQ0Ry9CTWEvSVFDdG92
            VWJqaFNFUWl5ZFNHNW0yY3Z2UmxIVEEKLS0tIEQ1Z2lXSGF2RXNEazVZcWEvbEEy
            b3VXNmo3WCtGMytrZmNjU2NXT1hQZ2cKcnZqut0haeOniZQcUNDX6BAYT3iy532k
            TDaJ2PhNi6TkuUfLeV78KV50+wdgD8M34Bptg3qF6JND/yCQKjRVWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T05:09:02Z"
    mac: ENC[AES256_GCM,data:ankZZQRakqG55jytiW3khlHaQjTPOkj4yW1+WbitSgVCZjC2f0wFFKrcf3Y99HEy4j+9OT15dr7ZeIL8NrxnBTk/HsSswasuXPP9KahkLOarLqtlnklVr4eY9AqaMxDUXzpwFHQqp4mNV0+dDztVaZHYplfmo2yB34L3YlD2ba4=,iv:NpYbBI6u5HJXeKs4/AmwFhfL8BWxSXBogOdVjUSL1nQ=,tag:o/X8vBo6SPFrO9qmTKwcbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Namespace
metadata:
    name: database
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNnJWKzdpZFl3azl6WVBS
            WkVPcFRLUlo3cEVUQ0FUa0lTbzY4S3BWMXpvCjJFdEh4MjQ0Ry9CTWEvSVFDdG92
            VWJqaFNFUWl5ZFNHNW0yY3Z2UmxIVEEKLS0tIEQ1Z2lXSGF2RXNEazVZcWEvbEEy
            b3VXNmo3WCtGMytrZmNjU2NXT1hQZ2cKcnZqut0haeOniZQcUNDX6BAYT3iy532k
            TDaJ2PhNi6TkuUfLeV78KV50+wdgD8M34Bptg3qF6JND/yCQKjRVWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T05:09:02Z"
    mac: ENC[AES256_GCM,data:ankZZQRakqG55jytiW3khlHaQjTPOkj4yW1+WbitSgVCZjC2f0wFFKrcf3Y99HEy4j+9OT15dr7ZeIL8NrxnBTk/HsSswasuXPP9KahkLOarLqtlnklVr4eY9AqaMxDUXzpwFHQqp4mNV0+dDztVaZHYplfmo2yB34L3YlD2ba4=,iv:NpYbBI6u5HJXeKs4/AmwFhfL8BWxSXBogOdVjUSL1nQ=,tag:o/X8vBo6SPFrO9qmTKwcbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
