apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: apps
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:wLY/TEvqm7W63S1P8y9Nfkub,iv:iZhFVRrBNkJcUBZPjfmS4K5e2/P9KBE1V/x1z8e/uh4=,tag:RPL9Kckm2jQXyGmbC4pGtw==,type:str]
    client-secret: ENC[AES256_GCM,data:tH4OvLzf8qjaXJS9loQzBuAyhMmN8LSouWVkeLvKD5K/VCU22/sBpAL8xgQNGrfNHdZegd3cgnb/WlbWKHhHXg==,iv:ATr2W64oqnF3SKvzo0Po2LymI/ZD5ArfSQynY/3e0GQ=,tag:mASk6P+p/Tp7yB6iDaGi3g==,type:str]
    cookie-secret: ENC[AES256_GCM,data:LCp4MRnu/0ZqeHCOiqWZMm+MGUTBba97EFcDDI0qIlfT5aBDCqh/5dj2azI=,iv:Vjt0jVn6LFsytixOubosb9xKCDPiLuNePF6nGejzzUQ=,tag:pwjWYH3YU7TlrU4lKMVJ5A==,type:str]
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWStCc3l6ZHh4MmlEdUtP
            TFlSUHhwQmpBbVhkZVpzZXV6QmU3MzBFSEVFCkQrNFlPT3J4MGNCSlZDeTFJYWxj
            d3NwL1dGMFBaNmFUd3QrYmhjbHRqZTQKLS0tIEdxSnF0MWNoOGxha08vZVhlaU1q
            RUJHQUd6cTFUMmZOdG9YOTBBUFRxaE0Ktp+F9jnb8ZCHP5AHNIsf15K3PGSH8d0U
            QCC2aE0K1p8pZCVhzLU1MfuF+rkJPHGZa/b1a53LtNDfgNjQ/h9J0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T00:59:50Z"
    mac: ENC[AES256_GCM,data:/QsH6/DkpCSQZhXfNEzRF2dJDt3iNsD6DJ824H0oAM+fWjwaT1GPNrrcXnXXfTDo9yFDVA3RjvGOnC2WMMh2aGkCpZoz/vqp/05lkmBfLlJ7XpLQ0mN1Y/1J7/EbcLM6c+JbBduFdIGF7mIGbWSiDJNqX6CHqBZlGBbpqSmVvEI=,iv:SXubNzaiGXGhBEu5WEaGYQjHsY/VfwkLJz41fuBYhXc=,tag:8XFuRhSfL2oXgf9erFIQFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
