apiVersion: v1
kind: Secret
metadata:
    name: pgadmin4
    namespace: database
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:/uzGe0zl5MWX,iv:32bHckd3ab/CIgCcluUNoM+7FiFKzHFT4CnVnQoSs60=,tag:g27SXlU7rLmXvhdgcq/eHA==,type:str]
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bFpKbUtlRlBZMURNOHFR
            blBhVytUK1NGUHhlbGxwWUR0M2ZtUnN2VUZvCjJBcHVPVEppOGRsQUdvODh5eTlr
            NFE4cnl6TVJXenBITHZXWDgyRng5SjQKLS0tIE5iVUJhcENCUWsrVUt2ZERJTEph
            OU5ONjAxblcyOHhTRWk5bDkvd20rb0UKpNTMlqtTqSJxPkLnoO4hG0BTQH8oMyzn
            YOvmolps2wCbMJ/OQrr9L+75LC2KV9dFTfXEZU28oiJqChD+kIZPnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T05:08:31Z"
    mac: ENC[AES256_GCM,data:uqAxtJ41TyeycIB5cPIB0OE3Nx32vTcaXyY+C8aAFDhiJgkZXnEhy7oMHZqnJgU/KG/AKZDc9CgqYlT11QGuNfzXsFiqRGsRAy+GexyQow7K1OzMnsHa+g/BKQ4yOGm+VPN9WI506gf1eFNL6/rFZFwas74EO2ZHf1mCOvcHAKU=,iv:iTLkWAN0ZE+T619mOZr6ulREOHzmE4663hYZH1Y9Opg=,tag:uFvC/XMWn5AR1unWQMqMwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
