apiVersion: v1
kind: Secret
metadata:
    name: postgresql
    namespace: database
type: Opaque
stringData:
    postgres-username: ENC[AES256_GCM,data:DPCr2+aII1I=,iv:RsMQ8H1F4G2Lh0zuzcUcguGMpeUqjmaezEsAwbtGPDI=,tag:adthJld6dH9zg1HLQov3fw==,type:str]
    postgres-password: ENC[AES256_GCM,data:qdD1UOmlRxI=,iv:61WAbs++oX+PsVgSnKuQK5HOswyKi+CaECcKmToIWAY=,tag:+TmbCa7khi7zcZ9KL+VxeA==,type:str]
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYU21CSUJ6anAzazhpaWlD
            eDlXZUk1U3NzOXR3cGFMLzB6ckJiaTFEL1ZRCmN2dSsyWFFhVThqZVVDeURBU0VF
            L0U2cCtMWGpQR25OWCtxSjkyV1RwS2cKLS0tIFRvbENDdncveDZWcWpvaTlFa0lr
            K2FYRnBCc0lvc1ZqcFBwSy9XMUN3NW8KFHDN/7whfVToCPHz+9bTTHRW8aUD7TZS
            GtsOxHKgxad5LoejzP/onb+9DRjo51zX6Kzdz6XYz//tuFZZZNVjoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T11:09:50Z"
    mac: ENC[AES256_GCM,data:gFPEr/tHbhd+kKJE29FWM68ysd/sGrgltL1L3McZjPeS1/PLWJruL1y6zTlzvk81aMLH7wHBv60kOA7BlG4scEzxBKr6u7c1tpsaM2D+uAeNl8eil+0FrCMRhvZEwr3g4rIdEMy5vw8x8+iOvytbNUrzIeSxiyAPGwjr9r9D0ec=,iv:KjWTOp2Scyq3G+d0JZHsc/wrsOeyKZajV+7X3PSOaCI=,tag:wFFVG9G1YrRPcK1Rqe0iFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: postgresql
    namespace: apps
type: Opaque
stringData:
    postgres-username: ENC[AES256_GCM,data:r5GOiXX8/bQ=,iv:jUiACyZlNwtCrIuP3AgKHXTAOVSiXuPMDEfraQuqhg4=,tag:vCE2UMCf8X//2qeAnO+DzQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:qdD1UOmlRxI=,iv:61WAbs++oX+PsVgSnKuQK5HOswyKi+CaECcKmToIWAY=,tag:+TmbCa7khi7zcZ9KL+VxeA==,type:str]
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYU21CSUJ6anAzazhpaWlD
            eDlXZUk1U3NzOXR3cGFMLzB6ckJiaTFEL1ZRCmN2dSsyWFFhVThqZVVDeURBU0VF
            L0U2cCtMWGpQR25OWCtxSjkyV1RwS2cKLS0tIFRvbENDdncveDZWcWpvaTlFa0lr
            K2FYRnBCc0lvc1ZqcFBwSy9XMUN3NW8KFHDN/7whfVToCPHz+9bTTHRW8aUD7TZS
            GtsOxHKgxad5LoejzP/onb+9DRjo51zX6Kzdz6XYz//tuFZZZNVjoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T11:09:50Z"
    mac: ENC[AES256_GCM,data:gFPEr/tHbhd+kKJE29FWM68ysd/sGrgltL1L3McZjPeS1/PLWJruL1y6zTlzvk81aMLH7wHBv60kOA7BlG4scEzxBKr6u7c1tpsaM2D+uAeNl8eil+0FrCMRhvZEwr3g4rIdEMy5vw8x8+iOvytbNUrzIeSxiyAPGwjr9r9D0ec=,iv:KjWTOp2Scyq3G+d0JZHsc/wrsOeyKZajV+7X3PSOaCI=,tag:wFFVG9G1YrRPcK1Rqe0iFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
