apiVersion: v1
kind: Secret
metadata:
    name: postgresql
    namespace: database
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:qdD1UOmlRxI=,iv:61WAbs++oX+PsVgSnKuQK5HOswyKi+CaECcKmToIWAY=,tag:+TmbCa7khi7zcZ9KL+VxeA==,type:str]
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYU21CSUJ6anAzazhpaWlD
            eDlXZUk1U3NzOXR3cGFMLzB6ckJiaTFEL1ZRCmN2dSsyWFFhVThqZVVDeURBU0VF
            L0U2cCtMWGpQR25OWCtxSjkyV1RwS2cKLS0tIFRvbENDdncveDZWcWpvaTlFa0lr
            K2FYRnBCc0lvc1ZqcFBwSy9XMUN3NW8KFHDN/7whfVToCPHz+9bTTHRW8aUD7TZS
            GtsOxHKgxad5LoejzP/onb+9DRjo51zX6Kzdz6XYz//tuFZZZNVjoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T03:27:31Z"
    mac: ENC[AES256_GCM,data:L+ockatH4sQ4j7yVa2lWhH1XTlefLSEi1LBzuHilB9owyH5+MnLbRd+IJrqOa1k4d50ESeCBFBRf6HWxxWt8xCXaPa6B0kwZJZaDoZ7GN187zwWDJu9JkH8Jm+p3GRU5F9moYzNjZRvy6ANi8Fldu33ACxMrDrue+QaJgMXMlAI=,iv:QTSpwQ03xUYXKehOU7FzwAIC+0URcp+ja/1naMvHCXs=,tag:L61h/P35HBE5O9xTf+KusQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
