apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:HxtqNH4ckHQ9VyKknb5URPM=,iv:xvMErwA5DVeFQoedo3I4LDYyMyz5JxiamjQAocb7Evk=,tag:uh0WEJ0nXFYo3nL7GZZzXA==,type:str]
    client_secret: ENC[AES256_GCM,data:E6fQ8pSklps8akY/5c+dvk+y7covhOScWA67p7YybomET5TDoCpJMxofklkh+yCAvzMjkMZdtVtcXVPgUh6b,iv:72Dyxw2Z5HwDZBSw5HuBiKmuaH5WnmRmltPKZwf2KL4=,tag:JrYd7AhjZ6ISkCcS1nqRig==,type:str]
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJczZCWlpnTHVCRHlhVlFw
            ZWVWT1gyWDJDd1lsaVBCSVhKRDJIc0cyc1hrCll0VkxWQjVpb05PdytsOVBtZ0Nn
            bVljRUNRUW01NTB5M3FLenFRbkNsaDQKLS0tIEUzQmFtdTVTZVcwaWJVdndOUFpH
            ZFUvMzdXTHd5ZUUwdzNsbGNsNXBvUlUKW/SAoSG8N2cJYt92IH1ERGpnyXgo4kcL
            7k37v85yZvI5aLXiw3JAjTvPz6YShzqulbe9tCtScBA1HzJtbwnK4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T04:56:32Z"
    mac: ENC[AES256_GCM,data:ZRr3OdupdZPWOMmJzILHB8phztvS/V7bM4WOYJ1MdlHcCt1ChYQjaI+1Dga3IEXByEE22wmy4j8u+r5CKnJvHbC2R8PhNyMuOtZAygXiUOj9Aia/Zi/a6AyHMWxYqlib3szMSdBJ3TendpDyhdtyQkwzx1GyEbzCdwC2N5hYGCY=,iv:B0m8qYFxS0tkUMSBu9Vvr8qJQKEqbsm8qzqs0QDyO1A=,tag:z3guO2YaDAOWROqFyt4feg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
