apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-push
    namespace: apps
type: Opaque
stringData:
    installationId: ENC[AES256_GCM,data:KX85ytncKF0MJdjK80YDvh1KuffhvwPTgqhj1U5ai2dzVJJ0,iv:FLbHCWbjsC9jXzYirEAbmJep8/dFx7srasGTu1D9x1I=,tag:O3Wv5XF51PpjRJEXj772Pg==,type:str]
    installationKey: ENC[AES256_GCM,data:2s5K4P5UMX/aM91QUM2h4qjQT5w=,iv:OvAly9ROteCE4xuuVL8fwx41Onr2tfVQ4E1QdYSdHcI=,tag:5Ww8bHFKYYSyIOXYjVOltw==,type:str]
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEV2ZTckRqM0FlVU4yYTRh
            RmRESlIxRVI3L0JDTk1NWU9ZMi9xRDlTUlZzCjh2TVRrcmh6cmhydUhyb1UwK09t
            TDMyRjNvVkNOTTJYSTRsK0FMRk9vSVEKLS0tIGtpNWVFT21yZFBvVlFkUDBPWExE
            VE1uNm92Tk9QL0JuSHVEL0pTTm80eEUK6htPQIxCsi1X/R2u5lNNLZXs1NqWarMK
            8vjXcSH6cNH4jFp2s7wmyB4YbgmSxnoJfIh5suY8c6+danq4apZCQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T07:45:06Z"
    mac: ENC[AES256_GCM,data:u57ALwghAzMPcOC40TCm7R0Ebp5d4gP9INdjY4L277bl0245HKKjQrg7dubkScQRWCgfXatJRImtEoqBvYMhUziV5naSCwhQx2/0Y/b/vtkax+8h3nHwAVlSuaV7rxNk7DIx87CzJlXfaWuTkOhqHx6wSvjY6lvkG3HYJZcv5qY=,iv:o+3tl9ttq0VY9Feq0ChEd+XF0JfbYW4T2BahfTXlffk=,tag:JhypBTuR/W/hrpXvKgGdHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-admin-token
    namespace: apps
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:3j916YpvJ3x7b+jWxGbVBnJFqslbhdNSWVXKzXKPJ1MUmbyzLdfFuJv6we9bzmKtdVWBN65m84Dn5E3Cpj5QPw==,iv:gCzMmO7GTWZnUaOcOEDEwvY8eBT/rqFyMKOal08YdNs=,tag:w41n02yXytLC96dY+ufmPA==,type:str]
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEV2ZTckRqM0FlVU4yYTRh
            RmRESlIxRVI3L0JDTk1NWU9ZMi9xRDlTUlZzCjh2TVRrcmh6cmhydUhyb1UwK09t
            TDMyRjNvVkNOTTJYSTRsK0FMRk9vSVEKLS0tIGtpNWVFT21yZFBvVlFkUDBPWExE
            VE1uNm92Tk9QL0JuSHVEL0pTTm80eEUK6htPQIxCsi1X/R2u5lNNLZXs1NqWarMK
            8vjXcSH6cNH4jFp2s7wmyB4YbgmSxnoJfIh5suY8c6+danq4apZCQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T07:45:06Z"
    mac: ENC[AES256_GCM,data:u57ALwghAzMPcOC40TCm7R0Ebp5d4gP9INdjY4L277bl0245HKKjQrg7dubkScQRWCgfXatJRImtEoqBvYMhUziV5naSCwhQx2/0Y/b/vtkax+8h3nHwAVlSuaV7rxNk7DIx87CzJlXfaWuTkOhqHx6wSvjY6lvkG3HYJZcv5qY=,iv:o+3tl9ttq0VY9Feq0ChEd+XF0JfbYW4T2BahfTXlffk=,tag:JhypBTuR/W/hrpXvKgGdHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-extra-vars
    namespace: apps
type: Opaque
stringData:
    SSO_CLIENT_ID: ENC[AES256_GCM,data:FogkFJVrt7jQvJL/8SLBPewL,iv:q+4X47NuoSwH0qFAgXLP82BEgmQRIaBuhaiJDUXXSQ8=,tag:Z3o/pOrx6/+lq3jCu5KUuQ==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:mPzmvWPrEuEJuRtBraPsCxR/DnPh6h/pzgdI3yeuSKyMQ9DeqDPRVdefL2JG0Kl7yx/bFjk3BaBvHwK8kkmERg==,iv:1nJWFyjhyn74pbm9FU3+Dbv8qrsOOr29IJPgziseHOA=,tag:y7UdJe9JqOmO/WcdmcVD3Q==,type:str]
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEV2ZTckRqM0FlVU4yYTRh
            RmRESlIxRVI3L0JDTk1NWU9ZMi9xRDlTUlZzCjh2TVRrcmh6cmhydUhyb1UwK09t
            TDMyRjNvVkNOTTJYSTRsK0FMRk9vSVEKLS0tIGtpNWVFT21yZFBvVlFkUDBPWExE
            VE1uNm92Tk9QL0JuSHVEL0pTTm80eEUK6htPQIxCsi1X/R2u5lNNLZXs1NqWarMK
            8vjXcSH6cNH4jFp2s7wmyB4YbgmSxnoJfIh5suY8c6+danq4apZCQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T07:45:06Z"
    mac: ENC[AES256_GCM,data:u57ALwghAzMPcOC40TCm7R0Ebp5d4gP9INdjY4L277bl0245HKKjQrg7dubkScQRWCgfXatJRImtEoqBvYMhUziV5naSCwhQx2/0Y/b/vtkax+8h3nHwAVlSuaV7rxNk7DIx87CzJlXfaWuTkOhqHx6wSvjY6lvkG3HYJZcv5qY=,iv:o+3tl9ttq0VY9Feq0ChEd+XF0JfbYW4T2BahfTXlffk=,tag:JhypBTuR/W/hrpXvKgGdHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
