apiVersion: v1
kind: Secret
metadata:
    name: velero-r2-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:tcV1RUI6b49Orv2yE8WgOBBexoVHAO4Fgi3YzepR6/sNASeqDBjQE9F/SNTpraTMozqHXkXW2SUDkOtW6x9k0i3hHqwJHV6iT4e6BeAXGYzBNRnFLax7d9GZ6vnTzp7RsmaWCoq1CMDmAsH1dN8rae4YrI49lL818KyrkGw1yr4Ddz+A1kZxUNVOyO8LgnJ2qi1+8A==,iv:CwynQs0xaSdKYfybG7UrN3bEc4vGHXrfQU6LrmrTulk=,tag:KA6iTQcPk2n50mASBPqWHA==,type:str]
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bm9UM01pK1J6K3IveTNk
            YUZKM3Y1czRBenRMM1RudElsWFJwaG8xUjE4Clc4SUlmRlRvWElVMGVPMXZJcHlY
            dU1wNi9MR293OFlSdHFkUkQvNmZyQVEKLS0tIGFjRVYwWDdpcHZ2dkpiajh2d0lQ
            UmtiQ2hBM1RXVWRzaXJINjVJaWIxWjQKK26dJ8lIEe+ExIeDMvQ/oGq/2NT+kJd7
            wtUGHGhwlX8x/aPJbgWAN/p1lkgVjMM+q/D971xcR1gpxzZu2h1JvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T04:42:05Z"
    mac: ENC[AES256_GCM,data:NNpNXXuuJ9pEyhwYwJvbwBIGV6seFOIGucX7MqEOLQJKut0Op47/GiV/JM/PFW05x8nYdCdSJq4EeUTgAWtiDyA3AMmqNYP9O2YQ8GOruVanvOkxsZzGf76HIye0mzWzlIlr3ZdBJ3GCLO2cswyvIQZUCxn2p4jsG+T3x/G5WMM=,iv:z6Bz5NA+cPNGh28kte0FLwiZKBffCdOyKblRrYmK/14=,tag:Sa5fbG04MA9zFTiZZKDdvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
