apiVersion: v1
kind: Secret
metadata:
    name: zitadel-master-key
    namespace: apps
type: Opaque
stringData:
    masterkey: ENC[AES256_GCM,data:l/N08UWnlJRTxtNSD7rYrhssnSXwiiUILQRa+LkFRKg=,iv:sku1Q7czYLf1bC/MDq11exfzpicDNTcBpan9qiHQzGM=,tag:+NPa98eUwJPg0+g4BxjDSQ==,type:str]
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZXlTS2NJakpNOE95L2U0
            T2ZETHl2ZVFxZ01RWWtNanBiWm9pZ1ZKeUF3ClQ0M1Uwc1JVdWZiOEdFRWZKeDhh
            ZlUxYkhwQmhZOHZ5VnoxdkdCZGhNNDAKLS0tIFpWUHlzYTNEYjZmS0pGdURmdGVv
            VzNIWGdWd0R2eDVNT3FVVzFqMXpadDgKVzgJNRwgsYwUn54TAkR7/4H8QfqKc5gv
            MOHAZWIIIxW+kaMyoM0kzt6lhAaeQXBMReinuTeH/BHUDKtMS+KnFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T08:15:06Z"
    mac: ENC[AES256_GCM,data:GmjdS7cQ93+U1BDAvCdrQmDeYCUKAqMVABG/z5cdNcPLDupb8JgFn6L5Fw9VtJ3EsJ8i6dMc/jsHPKAXS2bDPL0wIjY/O8nuZQd2o55EzvMTvq206+NUHBtiUsgGtBKcg+vyCL4Z0tgu+OQXAabb7p/FMnKE5rxd/PpcmJrpiJQ=,iv:uLvfm4IywODSIdSNc4MQwlzoAracV/C1rmWRIyfxdxE=,tag:41C/FixfgvXkfNRK6XV+fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: zitadel-default-human
    namespace: apps
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:GeAybMOewFNF,iv:ba7MuWxj7VLTMsXbOAaZkTz+HO2o8XGaeOD2X2kP260=,tag:4WhOrnsfe+/CFM1+Vfboaw==,type:str]
sops:
    age:
        - recipient: age19xusndq3dlvwp75nklgtmfne7r5fe0rhqld8j7wkawxc5h9usurqpsqrxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZXlTS2NJakpNOE95L2U0
            T2ZETHl2ZVFxZ01RWWtNanBiWm9pZ1ZKeUF3ClQ0M1Uwc1JVdWZiOEdFRWZKeDhh
            ZlUxYkhwQmhZOHZ5VnoxdkdCZGhNNDAKLS0tIFpWUHlzYTNEYjZmS0pGdURmdGVv
            VzNIWGdWd0R2eDVNT3FVVzFqMXpadDgKVzgJNRwgsYwUn54TAkR7/4H8QfqKc5gv
            MOHAZWIIIxW+kaMyoM0kzt6lhAaeQXBMReinuTeH/BHUDKtMS+KnFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T08:15:06Z"
    mac: ENC[AES256_GCM,data:GmjdS7cQ93+U1BDAvCdrQmDeYCUKAqMVABG/z5cdNcPLDupb8JgFn6L5Fw9VtJ3EsJ8i6dMc/jsHPKAXS2bDPL0wIjY/O8nuZQd2o55EzvMTvq206+NUHBtiUsgGtBKcg+vyCL4Z0tgu+OQXAabb7p/FMnKE5rxd/PpcmJrpiJQ=,iv:uLvfm4IywODSIdSNc4MQwlzoAracV/C1rmWRIyfxdxE=,tag:41C/FixfgvXkfNRK6XV+fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
