---
all:
  children:
    k3s_masters:
      hosts:
        master-1:
          ansible_host: "192.168.139.203"
          public_ip: "192.168.139.203"
          ansible_user: root
          ansible_ssh_pass: "{{ vault_ssh_passwords['master-1'] }}"
          k3s_node_labels:
            - "node.kubernetes.io/role=master"
            # - "topology.kubernetes.io/zone=hetzner-fsn1"
            # - "node.kubernetes.io/instance-type=cx21"

    k3s_workers:
      hosts:
        worker-1:
          ansible_host: "192.168.139.151"
          public_ip: "192.168.139.151"
          ansible_user: root
          ansible_ssh_pass: "{{ vault_ssh_passwords['worker-1'] }}"
          k3s_node_labels:
            - "node.kubernetes.io/role=worker"
        worker-2:
          ansible_host: "192.168.139.81"
          public_ip: "192.168.139.81"
          ansible_user: root
          ansible_ssh_pass: "{{ vault_ssh_passwords['worker-2'] }}"
          k3s_node_labels:
            - "node.kubernetes.io/role=worker"
