---
all:
  children:
    k3s_masters:
      hosts:
        master-1:
          public_ip: "1.2.3.4"
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519

    k3s_workers:
      hosts:
        worker-1:
          public_ip: "5.6.7.8"
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        worker-2:
          public_ip: "9.10.11.12"
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
