---
all:
  children:
    k3s_masters:
      hosts:
        akile-hkg:
          ansible_host: "{{ vault_ansible_hosts['akile'] }}"
          ansible_user: "{{ vault_ansible_users['akile'] }}"
          ansible_ssh_pass: "{{ vault_ssh_passwords['akile'] }}"
          k3s_node_labels:
            - "node.kubernetes.io/role=master"
            - "storage-node=true"

    k3s_workers:
      hosts:
        racknerd-35efd76:
          ansible_host: "{{ vault_ansible_hosts['racknerd'] }}"
          ansible_user: "{{ vault_ansible_users['racknerd'] }}"
          ansible_ssh_pass: "{{ vault_ssh_passwords['racknerd'] }}"
          k3s_node_labels:
            - "node.kubernetes.io/role=worker"
            - "external-dns=public"
            - "tailscale-proxy=true"
        oracle-a1:
          ansible_host: "{{ vault_ansible_hosts['oracle'] }}"
          ansible_user: "{{ vault_ansible_users['oracle'] }}"
          ansible_ssh_pass: "{{ vault_ssh_passwords['oracle'] }}"
          k3s_node_labels:
            - "node.kubernetes.io/role=worker"
