---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@{{ .Values.domain }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
            email: admin@{{ .Values.domain }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@{{ .Values.domain }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
            email: admin@{{ .Values.domain }}
---
# 公网域名证书
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: public-wildcard-tls
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: public-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "{{ .Values.publicDomain }}"
    - "*.{{ .Values.publicDomain }}"

---
# Tailscale 域名证书
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tailscale-wildcard-tls
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: tailscale-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "{{ .Values.domain }}"
    - "*.{{ .Values.domain }}"
