---
# Gateway API with custom Traefik
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Gateway API CRDs (standard channel)
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml
  - gatewayclass.yaml
  - gateway.yaml
