---
# Disable built-in Traefik (set to false to use K3s bundled Traefik)
k3s_disable_traefik: true

# Extra TLS SANs for API server certificate
k3s_tls_san_extra: []

# Fetch kubeconfig to local machine after install
k3s_fetch_kubeconfig: true
