---
galaxy_info:
  role_name: k3s-agent
  author: infra-k3s
  description: Install and configure K3s agent (worker node)
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: EL
      versions:
        - "8"
        - "9"

dependencies:
  - role: k3s-prereq
