# Example application template
# Uncomment and customize to deploy your applications

# Example: Deploy a simple web application
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: myapp
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://charts.bitnami.com/bitnami
#     chart: nginx
#     targetRevision: 18.2.5
#     helm:
#       releaseName: myapp
#       values: |
#         service:
#           type: ClusterIP
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: myapp
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
