---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://oauth2-proxy.github.io/manifests
    chart: oauth2-proxy
    targetRevision: 10.1.1
    helm:
      releaseName: oauth2-proxy
      values: |
        config:
          existingSecret: oauth2-proxy-secret
        extraArgs:
          provider: oidc
          user_id_claim: sub
          provider_display_name: ZITADEL
          redirect_url: "https://oauth2-proxy.{{ .Values.domain }}/oauth2/callback"
          oidc_issuer_url: "https://zitadel.{{ .Values.domain }}"
          email_domains: ["*"]
          pass_access_token: true
          skip_provider_button: true
          cookie_secure: true
          reverse_proxy: true

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
