---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://oauth2-proxy.github.io/manifests
    chart: oauth2-proxy
    targetRevision: 10.1.1
    helm:
      releaseName: oauth2-proxy
      values: |
        config:
          existingSecret: oauth2-proxy-secret
        extraArgs:
          provider: oidc
          user-id-claim: sub
          provider-display-name: ZITADEL
          redirect-url: "https://oauth2-proxy.{{ .Values.domain }}/oauth2/callback"
          oidc-issuer-url: "https://zitadel.{{ .Values.domain }}"
          email-domains: ["*"]
          pass-access-token: true
          pass-user-headers: true
          pass-authorization-header: true
          skip-provider-button: true
          cookie-secure: true
          set-xauthrequest: true
          reverse-proxy: true
          silence-ping-logging: true
          show-debug-on-error: true

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
