$ANSIBLE_VAULT;1.1;AES256
34626136613530373564336261646632383234363835313062613932303165613566303466303132
3936386430303233353061313133313830656638663562390a643035616465303862306564663461
61323662353766646539373065633830363134376237323566626231653062316439616565613961
3139346133383136340a323432623035366365356664653932353165636431343232643433636662
63613363663030383861613032626164363037383334643162663962666663343038396236393862
34313135396162653539376332633539303137383537343565353964323034376230613536373364
37666333383262393930303536383461653334376165643265663161653535633364373732383338
34343038633832633739346539643039353462393430363733363636656361636366666164363564
31636335326162346339323830343165313138303538356332376263633338373135343962656339
66353463336166636635313537666664383338333830646362646635313863386432396430306532
66303737373566653362376331383233323564336136346431643665613465666533333234356331
30363032656666313264303366346363306163663763313430386234303039303165333136396434
36323030363338376139613735313763323062633466313630653239653836386663336661383664
62333564643536646332373035333830663938336130376539663239663832653038316232626139
30613135373961323332623934613935653364616131336663633466343338306263663161383761
63653337623231333539303930663635383437353338656263656438343133633735323838653236
30373437353835343932393334393637316131373733306538663636363538373534653564623733
66386634623033346365303133333563336564316438313930616137383430306334346263336635
64643237393734663836306631636664663137636130616666636665393866363833313632393961
38623062633966653064303266303161323261643761623039663434643831666639303861663166
65396639383831333362326237306266396333336538393832613834336230323363333236653065
32666462636464633262333434343630623039396237663431366663376630623535333131623232
30663532613132303839363766313865383932396531643939366264633233333262333165393131
62636561663936333233
