$ANSIBLE_VAULT;1.1;AES256
61373032373662666632346436376164356637393436326462653462613236336239663536643631
6136373337353364396532373031383639366666373936610a646535663432633638303430336462
66376636336561363537343734396264316334323563366532353939343137366338373262366361
3533333064636565380a353636303331323038663738353734323865633965343837663064343263
65653638316161303135643165323131383461626232363161383263626335356137346135626463
33666565313134623736646164366438663434666664303237663332633132666232313636663230
30363934313235373233323266613765316235343761333037653361316462333032643661363739
61306465643837623733393738343761323430626365343835633930646236353065363331646333
34303135346564646163633732333336346463343231613537356364333730343735643433316534
63393537636537306632626164373261303936633830376364393761383236323366393863383237
32666435386232643762643733336134383564613761646266346463303634633933363332663661
34343164646432643363386334643631646636613731363730376134313034333137316235353836
38393761623630666534643164343839376561633137663333343431643963643964346335666338
33343761666135313636636562636535303230333962333262323430396632373239373738333865
32633334373366666266633332356664303039343633653837343233383835353336643534633331
36343130376463353135303764336436396533386538363861636436353634326663383534363566
36363837363836666339613538366335363234363965313363336139393338343937386635396530
34653137343161326337326266323531656466313036316635626564373031663866323434353363
39323639633561386562303839376234653237353933313635663761366135346231333832393435
35323165646564633461643838326162363631336564643831323565353831383234643863353464
37666230343832386332313561303965656233373535353565663763663364373038656265373364
32373963353734393965623232616564333030316261323132356531373830386538353135393463
34356565383462323038616432376132346464353165306266353433353266343832316131313135
64663230313835396532616663653834636463653461353232396435363837336636353335303233
36653137396163393431303638663533646665346437353836636135323162613139303764626539
30616239363231613834626637633031316166653835396637643933303566626238373330316231
35363530326130316564396139393638393361376432616532613962653938306130323038376230
30386432363638643131653937613732613937636231313932303239353934633630616366666663
3233
