---
- name: Reload UFW
  community.general.ufw:
    state: reloaded
  when: ansible_facts["os_family"] == "Debian"

- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  when: ansible_facts["os_family"] == "RedHat"
