---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Change to your app name
namespace: myapp

commonLabels:
  app.kubernetes.io/name: myapp
  app.kubernetes.io/part-of: myapp

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  # - secret.yaml  # Encrypt with SOPS before uncommenting
